### ISSUE TITLE
Make `pkgin` work out of the box.

### ISSUE THREAD

**Issue by vincentbernat** [cross-platform-actions/netbsd-builder#1]
Hey!

`pkgin` does not work out of the box because `/etc/profile` is only read by login shells and I suppose that the way it works, no login shell is invoked. Therefore, `PKG_PATH` variable is not read.

**Comment by carenas** [comment]
the variable in /etc/profile is not needed for `pkgin` to work, since it has its own configuration added at install time and will use that instead if PKG_PATH is not defined.

if you are having problems running pkgin, make sure to use sudo first

**Comment by vincentbernat** [comment]
You are right. I am not familiar with NetBSD and I was trying first to use `pkg_add`. I thought I did test with `pkgin` without sourcing `/etc/profile` and it failed, but I am unable to find the log file to prove it. Sorry for the noise.
