### ISSUE TITLE
Please include the X11 set in the installation

### ISSUE THREAD

**Issue by dbohdan** [cross-platform-actions/netbsd-builder#3]
Some non-GUI programs depend on it. For example, the binary package for the fairly popular [GraphicsMagick](http://www.graphicsmagick.org/) (`sudo pkgin install GraphicsMagick`) requires X libs.

**Comment by jacob-carlborg** [comment]
I'm not that familiar with NetBSD. Do you need all X11 sets or only some of them?

<img width="364" alt="Screenshot 2023-01-20 at 20 22 43" src="https://user-images.githubusercontent.com/306980/213787522-ecdf0793-c9b9-4170-a092-01947f8880d3.png">

**Comment by dbohdan** [comment]
I am not sure you can exclude any and have every package like GraphicsMagick work. Better install all. NetBSD won't boot to GUI by default even with an X server installed.

**Comment by jacob-carlborg** [comment]
Fixed in [v0.10.0](https://github.com/cross-platform-actions/action/releases/tag/v0.10.0).

**Comment by dbohdan** [comment]
Thanks! My project's test suite [now fully passes](https://github.com/dbohdan/hicolor/actions/runs/4025277383/jobs/6918322574).
